INSERT INTO
    catalog.genres (name)
VALUES
    ('Rock'),
    ('Pop'),
    ('Metal'),
    ('Jazz'),
    ('Clasica'),
    ('Electronica'),
    ('Folk'),
    ('World'),
    ('Country'),
    ('Latin'),
    ('Reggae'),
    ('Hip-Hop'),
    ('R&B'),
    ('Soul'),
    ('Funk'),
    ('Gospel'),
    ('Blues'),
    ('Punk'),
    ('Rap'),
    ('Indie'),
    ('Dance'),
    ('Latino'),
    ('Reggaeton'),
    ('Afro'),
    ('Afrobeat'),
    ('Dubstep'),
    ('Drum & Bass'),
    ('House'),
    ('Techno'),
    ('Trance'),
    ('Ambiental'),
    ('Progressiva'),
    ('Experimental'),
    ('Alternative'),
    ('Indie Rock'),
    ('Psychedelic'),
    ('Grunge'),
    ('Punk Rock'),
    ('Soft Rock');